apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: another-helmrelease
  namespace: dmqttdemo
spec:
  releaseName: dmqttdemo-dev
  chart:
    spec:
      chart: az-e4k 
      version: 0.1.0-amd64 # or arm64
      sourceRef:
        kind: HelmRepository
        name: another-repository
        namespace: dmqttdemo
  interval: 5m
